all:
	GOPATH='' GOROOT='/home/ritesh/go_c_ipc_shmem_named_semaphore/go_app/go_1_20_4/go' /home/ritesh/go_c_ipc_shmem_named_semaphore/go_app/go_1_20_4/go/bin/go build main.go

run: all
	./main

clean:
	 GOPATH='' GOROOT='/home/ritesh/go_c_ipc_shmem_named_semaphore/go_app/go_1_20_4/go' /home/ritesh/go_c_ipc_shmem_named_semaphore/go_app/go_1_20_4/go/bin/go clean
